# Release configuration for automatic release notes
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🧰 Maintenance
      labels:
        - chore
        - maintenance
    - title: ⚡ Performance
      labels:
        - performance
        - optimization
    - title: 🔒 Security
      labels:
        - security
    - title: Other Changes
      labels:
        - "*"